FROM tomcat

COPY mywebtest/target/mywebtest.war /usr/local/tomcat/webapps/mywebtest.war
# COPY mywebtest/target/mywebtest.war/ /usr/local/tomcat/webapps/mywebtest
# COPY sample.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
