FROM tomcat

COPY mywebtest/target/mywebtest.war /usr/local/tomcat/webapps/ROOT.war
COPY mywebtest/target/mywebtest.war/ /usr/local/tomcat/webapps/ROOT
# COPY sample.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
