node{
  def app

    stage('Clone') {
        checkout scm
    }

    stage('Build image') {
	sh 'pwd'
        sh 'ls -la'
	app = docker.build("stefbibi/nginx-jenkins-xavki19", "./19_JenkinsfileBuildImageDocker")
    }

    stage('Test image') {
        docker.image('stefbibi/nginx-jenkins-xavki19').withRun('-p 80:80') { c ->
        sh 'docker ps'
	sh 'sleep 120'
        sh 'cat /usr/share/nginx/html/index.html'
        sh 'curl localhost'
	     }
    }
}

