node{
  def app

    stage('Clone') {
        checkout scm
    }

    stage('Build image') {
	sh 'pwd'
        sh 'ls -la'
	app = docker.build("stefbibi/nginx-jenkins-xavki19", "./19_JenkinsfileBuildImageDocker")
    }

    stage('Test image') {
        docker.image('stefbibi/nginx-jenkins-xavki19').withRun('-p 80:80') { c ->
		sh 'hostname'
	        sh 'docker ps'
		sh 'sleep 120'
	        sh 'curl localhost'
	}
    }
}

